### ISSUE TITLE
Pytrack - TypeError: cannot create 'module' instances

### ISSUE THREAD

**Issue by tanmoydutta** [pycom/pycom-micropython-sigfox#106]
* The Pycom board LoPy with Pytrack
* The firmware version 
(sysname='LoPy', nodename='LoPy', release='1.10.2.b1', version='v1.8.6-849-g0af003a4 on 2017-11-24', machine='LoPy with ESP32', lorawan='1.0.0')

* Exact steps to cause this issue
    1. Updated LoPy Firmware to 1.10.2.b1
    2. Updated Pytrack DFU to 0.0.8
    3. Updated the library with the following files and in the following structure - 

/flash/lib/L76GNSS.py
/flash/lib/LIS2HH12.py
/flash/lib/pytrack.py
/flash/lib/mqtt.py
/flash/lib/pycoproc/pycoproc.py

   4. Rebooted the LoPy and accessed via the serial console and typed in the following command to get the error - 

>>> from pytrack import Pytrack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/flash/lib/pytrack.py", line 5, in <module>
TypeError: cannot create 'module' instances

**Comment by tanmoydutta** [comment]
pytrack.py and pycoproc.py needs to reside on the same path level.
