### ISSUE TITLE
'LoRa' object has no attribute 'Mesh'

### ISSUE THREAD

**Issue by mihammouda** [pycom/pycom-micropython-sigfox#489]
Traceback (most recent call last):
  File "main.py", line 67, in <module>
  File "/flash/lib/pymesh.py", line 42, in __init__
  File "/flash/lib/mesh_interface.py", line 44, in __init__
  File "/flash/lib/mesh_internal.py", line 111, in __init__
  File "/flash/lib/loramesh.py", line 65, in __init__
  File "/flash/lib/loramesh.py", line 114, in _lora_init
AttributeError: 'LoRa' object has no attribute 'Mesh'
Pycom MicroPython 1.20.2.r1 [v1.11-a5aa0b8] on 2020-09-09; LoPy4 with ESP32
Pybytes Version: 1.6.0

**Comment by peter-pycom** [comment]
I think you might have to provision the pymesh FW. https://docs.pycom.io/pybytes/pymeshintegration/provisioning/ If I misunderstood you feel free to reopen, but please provide more context
