### ISSUE TITLE
Fault in unix version

### ISSUE THREAD

**Issue by henriqueng** [pycom/pycom-micropython-sigfox#58]
Please include the following information when submitting a bug report:

* System: Ubuntu 16.04 LTS x64

* Environment setup:
    1. git clone https://github.com/pycom/pycom-micropython-sigfox.git
    2. cd pycom-micropython-sigfox/unix
    3. make axtls
    4. make

* Micropython test:
```   ./micropython
   MicroPython ccb10e3 on 2017-08-25; linux version
   Use Ctrl-D to exit, Ctrl-E for paste mode
   >>> print('Hello World')
   Segmentation fault (core dumped)
```

* make test:
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
cd ../tests && MICROPY_MICROPYTHON=../unix/micropython ./run-tests
FAIL  basics/0prelim.py
pass  basics/andor.py
FAIL  basics/array1.py
FAIL  basics/array_add.py
FAIL  basics/array_construct.py
FAIL  basics/array_construct2.py
skip  basics/array_construct_endian.py
FAIL  basics/array_q.py
FAIL  basics/assign1.py
FAIL  basics/async_await.py
FAIL  basics/async_await2.py
FAIL  basics/async_def.py
FAIL  basics/async_for.py
FAIL  basics/async_for2.py
FAIL  basics/async_with.py
FAIL  basics/async_with2.py
FAIL  basics/attrtuple1.py
FAIL  basics/bool1.py
FAIL  basics/boundmeth1.py
FAIL  basics/break.py
FAIL  basics/builtin_abs.py
FAIL  basics/builtin_allany.py
FAIL  basics/builtin_bin.py
FAIL  basics/builtin_callable.py
FAIL  basics/builtin_chr.py
FAIL  basics/builtin_compile.py
FAIL  basics/builtin_delattr.py
FAIL  basics/builtin_dir.py
FAIL  basics/builtin_divmod.py
pass  basics/builtin_ellipsis.py
FAIL  basics/builtin_eval.py
FAIL  basics/builtin_eval_error.py
FAIL  basics/builtin_hash.py
FAIL  basics/builtin_hex.py
FAIL  basics/builtin_id.py
FAIL  basics/builtin_issubclass.py
FAIL  basics/builtin_len1.py
FAIL  basics/builtin_minmax.py
FAIL  basics/builtin_oct.py
FAIL  basics/builtin_ord.py
FAIL  basics/builtin_override.py
FAIL  basics/builtin_pow.py
FAIL  basics/builtin_property.py
FAIL  basics/builtin_range.py
FAIL  basics/builtin_reversed.py
FAIL  basics/builtin_round.py
FAIL  basics/builtin_slice.py
FAIL  basics/builtin_sorted.py
FAIL  basics/builtin_sum.py
FAIL  basics/builtin_type.py
FAIL  basics/bytearray1.py
FAIL  basics/bytearray_add.py
FAIL  basics/bytearray_append.py
FAIL  basics/bytearray_construct.py
skip  basics/bytearray_construct_endian.py
FAIL  basics/bytearray_longint.py
FAIL  basics/bytearray_slice_assign.py
FAIL  basics/bytes.py
FAIL  basics/bytes_add.py
skip  basics/bytes_add_endian.py
pass  basics/bytes_compare.py
FAIL  basics/bytes_compare2.py
FAIL  basics/bytes_compare3.py
FAIL  basics/bytes_construct.py
skip  basics/bytes_construct_endian.py
FAIL  basics/bytes_count.py
FAIL  basics/bytes_find.py
FAIL  basics/bytes_format_modulo.py
FAIL  basics/bytes_gen.py
FAIL  basics/bytes_large.py
FAIL  basics/bytes_mult.py
FAIL  basics/bytes_partition.py
FAIL  basics/bytes_replace.py
FAIL  basics/bytes_split.py
FAIL  basics/bytes_strip.py
FAIL  basics/bytes_subscr.py
FAIL  basics/class1.py
FAIL  basics/class2.py
FAIL  basics/class3.py
FAIL  basics/class_bind_self.py
FAIL  basics/class_binop.py
FAIL  basics/class_call.py
FAIL  basics/class_contains.py
FAIL  basics/class_descriptor.py
FAIL  basics/class_emptybases.py
FAIL  basics/class_getattr.py
FAIL  basics/class_inherit1.py
FAIL  basics/class_inherit_mul.py
FAIL  basics/class_instance_override.py
FAIL  basics/class_item.py
FAIL  basics/class_new.py
FAIL  basics/class_number.py
FAIL  basics/class_staticclassmethod.py
FAIL  basics/class_store.py
FAIL  basics/class_store_class.py
FAIL  basics/class_str.py
FAIL  basics/class_super.py
FAIL  basics/class_super_object.py
FAIL  basics/class_use_other.py
FAIL  basics/closure1.py
FAIL  basics/closure2.py
FAIL  basics/closure_defargs.py
FAIL  basics/closure_manyvars.py
FAIL  basics/closure_namedarg.py
FAIL  basics/compare_multi.py
FAIL  basics/comprehension1.py
FAIL  basics/containment.py
FAIL  basics/continue.py
FAIL  basics/decorator.py
FAIL  basics/del_attr.py
FAIL  basics/del_deref.py
FAIL  basics/del_global.py
FAIL  basics/del_local.py
FAIL  basics/del_name.py
FAIL  basics/del_subscr.py
pass  basics/dict1.py
FAIL  basics/dict2.py
FAIL  basics/dict_clear.py
FAIL  basics/dict_construct.py
FAIL  basics/dict_copy.py
FAIL  basics/dict_del.py
FAIL  basics/dict_from_iter.py
FAIL  basics/dict_fromkeys.py
FAIL  basics/dict_get.py
FAIL  basics/dict_intern.py
FAIL  basics/dict_iterator.py
FAIL  basics/dict_pop.py
FAIL  basics/dict_popitem.py
FAIL  basics/dict_setdefault.py
FAIL  basics/dict_specialmeth.py
FAIL  basics/dict_update.py
FAIL  basics/dict_views.py
FAIL  basics/enumerate.py
FAIL  basics/equal.py
FAIL  basics/equal_class.py
FAIL  basics/errno1.py
FAIL  basics/except_match_tuple.py
FAIL  basics/exception1.py
FAIL  basics/exception_chain.py
FAIL  basics/exceptpoly.py
FAIL  basics/exceptpoly2.py
FAIL  basics/exec1.py
FAIL  basics/filter.py
FAIL  basics/floordivide.py
FAIL  basics/for1.py
FAIL  basics/for2.py
FAIL  basics/for3.py
FAIL  basics/for_break.py
FAIL  basics/for_range.py
FAIL  basics/for_return.py
FAIL  basics/frozenset1.py
FAIL  basics/frozenset_add.py
pass  basics/frozenset_binop.py
FAIL  basics/frozenset_copy.py
pass  basics/frozenset_difference.py
FAIL  basics/frozenset_set.py
FAIL  basics/fun1.py
FAIL  basics/fun2.py
FAIL  basics/fun3.py
FAIL  basics/fun_annotations.py
FAIL  basics/fun_calldblstar.py
FAIL  basics/fun_calldblstar2.py
FAIL  basics/fun_calldblstar3.py
FAIL  basics/fun_callstar.py
FAIL  basics/fun_callstardblstar.py
FAIL  basics/fun_defargs.py
FAIL  basics/fun_defargs2.py
FAIL  basics/fun_error.py
FAIL  basics/fun_kwargs.py
FAIL  basics/fun_kwonly.py
pass  basics/fun_kwonlydef.py
FAIL  basics/fun_kwvarargs.py
FAIL  basics/fun_largestate.py
FAIL  basics/fun_name.py
FAIL  basics/fun_str.py
FAIL  basics/fun_varargs.py
FAIL  basics/gc1.py
FAIL  basics/gen_yield_from.py
FAIL  basics/gen_yield_from_close.py
FAIL  basics/gen_yield_from_ducktype.py
FAIL  basics/gen_yield_from_exc.py
FAIL  basics/gen_yield_from_iter.py
FAIL  basics/gen_yield_from_send.py
FAIL  basics/gen_yield_from_stopped.py
FAIL  basics/gen_yield_from_throw.py
FAIL  basics/generator1.py
FAIL  basics/generator2.py
FAIL  basics/generator_args.py
FAIL  basics/generator_close.py
FAIL  basics/generator_closure.py
FAIL  basics/generator_exc.py
pass  basics/generator_return.py
FAIL  basics/generator_send.py
FAIL  basics/getattr.py
FAIL  basics/getattr1.py
FAIL  basics/getitem.py
FAIL  basics/globals_del.py
FAIL  basics/hasattr1.py
FAIL  basics/ifcond.py
FAIL  basics/int1.py
FAIL  basics/int2.py
FAIL  basics/int_big_and.py
pass  basics/int_big_and2.py
FAIL  basics/int_big_and3.py
FAIL  basics/int_big_cmp.py
FAIL  basics/int_big_div.py
FAIL  basics/int_big_error.py
FAIL  basics/int_big_lshift.py
FAIL  basics/int_big_mod.py
FAIL  basics/int_big_mul.py
FAIL  basics/int_big_or.py
FAIL  basics/int_big_or2.py
FAIL  basics/int_big_or3.py
FAIL  basics/int_big_pow.py
FAIL  basics/int_big_rshift.py
FAIL  basics/int_big_unary.py
FAIL  basics/int_big_xor.py
FAIL  basics/int_big_xor2.py
FAIL  basics/int_big_xor3.py
FAIL  basics/int_big_zeroone.py
FAIL  basics/int_bytes.py
FAIL  basics/int_constfolding.py
FAIL  basics/int_divmod.py
FAIL  basics/int_divzero.py
FAIL  basics/int_long.py
FAIL  basics/int_mpz.py
FAIL  basics/int_small.py
FAIL  basics/is_isnot.py
FAIL  basics/iter0.py
FAIL  basics/iter1.py
FAIL  basics/iter2.py
FAIL  basics/iter_of_iter.py
FAIL  basics/lambda1.py
FAIL  basics/lambda_defargs.py
FAIL  basics/lexer.py
FAIL  basics/list1.py
FAIL  basics/list_clear.py
FAIL  basics/list_compare.py
FAIL  basics/list_copy.py
FAIL  basics/list_count.py
FAIL  basics/list_extend.py
FAIL  basics/list_index.py
FAIL  basics/list_insert.py
FAIL  basics/list_mult.py
FAIL  basics/list_pop.py
FAIL  basics/list_remove.py
FAIL  basics/list_reverse.py
FAIL  basics/list_slice.py
FAIL  basics/list_slice_3arg.py
FAIL  basics/list_slice_assign.py
FAIL  basics/list_slice_assign_grow.py
FAIL  basics/list_sort.py
FAIL  basics/list_sum.py
FAIL  basics/map.py
FAIL  basics/memoryerror.py
FAIL  basics/memoryview1.py
FAIL  basics/memoryview2.py
FAIL  basics/memoryview_gc.py
FAIL  basics/module1.py
FAIL  basics/module2.py
FAIL  basics/namedtuple1.py
FAIL  basics/object1.py
FAIL  basics/object_dict.py
FAIL  basics/object_new.py
FAIL  basics/op_error.py
pass  basics/ordereddict1.py
pass  basics/ordereddict_eq.py
FAIL  basics/parser.py
FAIL  basics/print.py
FAIL  basics/python34.py
FAIL  basics/return1.py
FAIL  basics/scope.py
pass  basics/self_type_check.py
FAIL  basics/seq_unpack.py
FAIL  basics/set1.py
FAIL  basics/set_add.py
pass  basics/set_binop.py
FAIL  basics/set_clear.py
FAIL  basics/set_copy.py
FAIL  basics/set_difference.py
FAIL  basics/set_discard.py
FAIL  basics/set_intersection.py
FAIL  basics/set_isdisjoint.py
FAIL  basics/set_isfooset.py
FAIL  basics/set_iter.py
FAIL  basics/set_pop.py
pass  basics/set_remove.py
FAIL  basics/set_specialmeth.py
FAIL  basics/set_symmetric_difference.py
FAIL  basics/set_union.py
FAIL  basics/set_unop.py
FAIL  basics/set_update.py
FAIL  basics/setattr1.py
FAIL  basics/slice_attrs.py
FAIL  basics/slice_bignum.py
FAIL  basics/slots_bool_len.py
FAIL  basics/special_methods.py
FAIL  basics/string1.py
FAIL  basics/string_center.py
FAIL  basics/string_compare.py
FAIL  basics/string_count.py
FAIL  basics/string_cr_conversion.py
FAIL  basics/string_crlf_conversion.py
FAIL  basics/string_endswith.py
FAIL  basics/string_escape.py
FAIL  basics/string_find.py
FAIL  basics/string_format.py
Traceback (most recent call last):
  File "basics/string_format2.py", line 58, in <module>
  File "basics/string_format2.py", line 27, in test_fmt
NameError: name 'test' is not defined
FAIL  basics/string_format2.py
FAIL  basics/string_format_error.py
FAIL  basics/string_format_modulo.py
FAIL  basics/string_index.py
pass  basics/string_istest.py
FAIL  basics/string_join.py
FAIL  basics/string_large.py
FAIL  basics/string_mult.py
FAIL  basics/string_partition.py
FAIL  basics/string_replace.py
FAIL  basics/string_repr.py
FAIL  basics/string_rfind.py
FAIL  basics/string_rindex.py
FAIL  basics/string_rpartition.py
FAIL  basics/string_rsplit.py
FAIL  basics/string_slice.py
FAIL  basics/string_split.py
FAIL  basics/string_splitlines.py
FAIL  basics/string_startswith.py
FAIL  basics/string_strip.py
pass  basics/string_upperlow.py
FAIL  basics/struct1.py
FAIL  basics/struct2.py
FAIL  basics/subclass_classmethod.py
FAIL  basics/subclass_native1.py
FAIL  basics/subclass_native2_list.py
FAIL  basics/subclass_native2_tuple.py
FAIL  basics/subclass_native3.py
FAIL  basics/subclass_native4.py
FAIL  basics/subclass_native5.py
FAIL  basics/subclass_native_buffer.py
FAIL  basics/subclass_native_cmp.py
FAIL  basics/subclass_native_specmeth.py
FAIL  basics/syntaxerror.py
pass  basics/sys1.py
pass  basics/true_value.py
FAIL  basics/try1.py
FAIL  basics/try2.py
FAIL  basics/try3.py
FAIL  basics/try4.py
pass  basics/try_as_var.py
FAIL  basics/try_continue.py
pass  basics/try_error.py
pass  basics/try_finally1.py
FAIL  basics/try_finally2.py
pass  basics/try_finally_loops.py
FAIL  basics/try_finally_return.py
FAIL  basics/try_finally_return2.py
pass  basics/try_reraise.py
pass  basics/try_reraise2.py
FAIL  basics/tuple1.py
FAIL  basics/tuple_compare.py
FAIL  basics/tuple_count.py
FAIL  basics/tuple_index.py
FAIL  basics/tuple_mult.py
FAIL  basics/types1.py
FAIL  basics/types2.py
FAIL  basics/unary_op.py
FAIL  basics/unboundlocal.py
FAIL  basics/unpack1.py
FAIL  basics/while1.py
FAIL  basics/while_cond.py
FAIL  basics/while_nest_exc.py
FAIL  basics/with1.py
FAIL  basics/with_break.py
FAIL  basics/with_continue.py
FAIL  basics/with_return.py
FAIL  basics/zip.py
FAIL  cmdline/cmd_optimise.py
FAIL  cmdline/cmd_showbc.py
FAIL  cmdline/cmd_verbose.py
FAIL  cmdline/repl_basic.py
FAIL  cmdline/repl_cont.py
skip  cmdline/repl_emacs_keys.py
FAIL  extmod/btree1.py
FAIL  extmod/framebuf1.py
pass  extmod/machine1.py
FAIL  extmod/machine_pinbase.py
FAIL  extmod/machine_pulse.py
FAIL  extmod/ticks_diff.py
FAIL  extmod/time_ms_us.py
FAIL  extmod/ubinascii_a2b_base64.py
FAIL  extmod/ubinascii_b2a_base64.py
pass  extmod/ubinascii_crc32.py
FAIL  extmod/ubinascii_hexlify.py
FAIL  extmod/ubinascii_unhexlify.py
FAIL  extmod/uctypes_array_assign_le.py
FAIL  extmod/uctypes_array_assign_native_le.py
FAIL  extmod/uctypes_bytearray.py
FAIL  extmod/uctypes_le.py
FAIL  extmod/uctypes_le_float.py
FAIL  extmod/uctypes_native_float.py
FAIL  extmod/uctypes_native_le.py
FAIL  extmod/uctypes_ptr_le.py
FAIL  extmod/uctypes_ptr_native_le.py
FAIL  extmod/uctypes_sizeof.py
FAIL  extmod/uctypes_sizeof_native.py
pass  extmod/uhashlib_sha1.py
pass  extmod/uhashlib_sha256.py
Traceback (most recent call last):
  File "extmod/uheapq1.py", line 27, in <module>
  File "extmod/uheapq1.py", line 19, in pop_and_print
NameError: name 'heapq' is not defined
FAIL  extmod/uheapq1.py
FAIL  extmod/ujson_dumps.py
FAIL  extmod/ujson_dumps_extra.py
FAIL  extmod/ujson_dumps_float.py
FAIL  extmod/ujson_load.py
FAIL  extmod/ujson_loads.py
FAIL  extmod/ujson_loads_float.py
FAIL  extmod/urandom_basic.py
FAIL  extmod/urandom_extra.py
FAIL  extmod/ure1.py
FAIL  extmod/ure_error.py
FAIL  extmod/ure_group.py
FAIL  extmod/ure_namedclass.py
FAIL  extmod/ure_split.py
FAIL  extmod/ure_split_empty.py
pass  extmod/uzlib_decompio.py
pass  extmod/uzlib_decompio_gz.py
FAIL  extmod/uzlib_decompress.py
skip  extmod/vfs_fat_fileio.py
skip  extmod/vfs_fat_fsusermount.py
skip  extmod/vfs_fat_oldproto.py
skip  extmod/vfs_fat_ramdisk.py
FAIL  float/array_construct.py
FAIL  float/builtin_float_minmax.py
pass  float/builtin_float_round.py
FAIL  float/bytearray_construct.py
FAIL  float/bytes_construct.py
pass  float/cmath_fun.py
FAIL  float/cmath_fun_special.py
skip  float/complex1.py
FAIL  float/float1.py
pass  float/float2int.py
Traceback (most recent call last):
  File "float/float2int_doubleprec.py", line 42, in <module>
NameError: name 'testpass' is not defined
FAIL  float/float2int_doubleprec.py
pass  float/float2int_fp30.py
FAIL  float/float_array.py
FAIL  float/float_divmod.py
FAIL  float/float_divmod_relaxed.py
FAIL  float/float_struct.py
skip  float/int_big_float.py
FAIL  float/int_divzero.py
FAIL  float/int_power.py
FAIL  float/list_index.py
Traceback (most recent call last):
  File "float/math_fun.py", line 39, in <module>
NameError: name 'test_values' is not defined
FAIL  float/math_fun.py
pass  float/math_fun_bool.py
Traceback (most recent call last):
  File "float/math_fun_special.py", line 36, in <module>
  File "float/math_fun_special.py", line 34, in <module>
NameError: name 'function' is not defined
FAIL  float/math_fun_special.py
FAIL  float/string_format.py
Traceback (most recent call last):
  File "float/string_format2.py", line 103, in <module>
  File "float/string_format2.py", line 26, in test_fmt
NameError: name 'test' is not defined
FAIL  float/string_format2.py
FAIL  float/string_format_fp30.py
FAIL  float/string_format_modulo.py
FAIL  float/string_format_modulo2.py
skip  float/true_value.py
skip  float/types.py
FAIL  import/gen_context.py
FAIL  import/gen_context2.py
FAIL  import/import1a.py
FAIL  import/import1b.py
FAIL  import/import2a.py
FAIL  import/import3a.py
FAIL  import/import_file.py
FAIL  import/import_pkg1.py
FAIL  import/import_pkg2.py
FAIL  import/import_pkg3.py
FAIL  import/import_pkg4.py
FAIL  import/import_pkg5.py
FAIL  import/import_pkg6.py
FAIL  import/rel_import_inv.py
FAIL  import/try_module.py
FAIL  io/argv.py
FAIL  io/buffered_writer.py
FAIL  io/bytesio_ext.py
FAIL  io/file1.py
FAIL  io/file_iter.py
FAIL  io/file_long_read.py
FAIL  io/file_long_read2.py
FAIL  io/file_long_read3.py
FAIL  io/file_readinto.py
FAIL  io/file_readinto_len.py
FAIL  io/file_readline.py
FAIL  io/file_seek.py
FAIL  io/file_stdio.py
pass  io/file_with.py
FAIL  io/open_append.py
FAIL  io/open_plus.py
FAIL  io/stringio1.py
FAIL  io/stringio_with.py
FAIL  io/write_ext.py
FAIL  micropython/const.py
FAIL  micropython/const2.py
FAIL  micropython/const_error.py
FAIL  micropython/decorator.py
FAIL  micropython/decorator_error.py
FAIL  micropython/emg_exc.py
FAIL  micropython/heap_lock.py
FAIL  micropython/heapalloc.py
FAIL  micropython/meminfo.py
FAIL  micropython/memstats.py
skip  micropython/native_closure.py
skip  micropython/native_const.py
skip  micropython/native_misc.py
FAIL  micropython/opt_level.py
skip  micropython/viper_addr.py
skip  micropython/viper_args.py
skip  micropython/viper_binop_arith.py
skip  micropython/viper_binop_comp.py
skip  micropython/viper_binop_comp_imm.py
skip  micropython/viper_binop_multi_comp.py
skip  micropython/viper_cond.py
skip  micropython/viper_error.py
skip  micropython/viper_misc.py
skip  micropython/viper_ptr16_load.py
skip  micropython/viper_ptr16_store.py
skip  micropython/viper_ptr32_load.py
skip  micropython/viper_ptr32_store.py
skip  micropython/viper_ptr8_load.py
skip  micropython/viper_ptr8_store.py
skip  micropython/viper_subscr.py
FAIL  misc/features.py
FAIL  misc/non_compliant.py
FAIL  misc/non_compliant_lexer.py
Traceback (most recent call last):
  File "misc/print_exception.py", line 32, in <module>
  File "misc/print_exception.py", line 32, in <module>
  File "misc/print_exception.py", line 13, in print_exc
NameError: name 'io' is not defined
FAIL  misc/print_exception.py
FAIL  misc/recursion.py
FAIL  misc/recursive_data.py
Traceback (most recent call last):
  File "misc/recursive_iternext.py", line 40, in <module>
  File "misc/recursive_iternext.py", line 36, in <module>
NameError: name 'N' is not defined
FAIL  misc/recursive_iternext.py
FAIL  misc/rge_sm.py
FAIL  misc/sys_exc_info.py
FAIL  stress/dict_copy.py
FAIL  stress/dict_create.py
FAIL  stress/list_sort.py
FAIL  unicode/file1.py
FAIL  unicode/file2.py
pass  unicode/unicode.py
pass  unicode/unicode_chr.py
FAIL  unicode/unicode_id.py
FAIL  unicode/unicode_index.py
FAIL  unicode/unicode_iter.py
FAIL  unicode/unicode_ord.py
FAIL  unicode/unicode_pos.py
FAIL  unicode/unicode_str_format.py
FAIL  unicode/unicode_str_modulo.py
FAIL  unicode/unicode_subscr.py
FAIL  unix/extra_coverage.py
FAIL  unix/ffi_callback.py
FAIL  unix/ffi_float.py
FAIL  unix/ffi_float2.py
518 tests performed (17778 individual testcases)
38 tests passed
32 tests skipped: array_construct_endian bytearray_construct_endian bytes_add_endian bytes_construct_endian repl_emacs_keys vfs_fat_fileio vfs_fat_fsusermount vfs_fat_oldproto vfs_fat_ramdisk complex1 int_big_float true_value types native_closure native_const native_misc viper_addr viper_args viper_binop_arith viper_binop_comp viper_binop_comp_imm viper_binop_multi_comp viper_cond viper_error viper_misc viper_ptr16_load viper_ptr16_store viper_ptr32_load viper_ptr32_store viper_ptr8_load viper_ptr8_store viper_subscr
480 tests failed: 0prelim array1 array_add array_construct array_construct2 array_q assign1 async_await async_await2 async_def async_for async_for2 async_with async_with2 attrtuple1 bool1 boundmeth1 break builtin_abs builtin_allany builtin_bin builtin_callable builtin_chr builtin_compile builtin_delattr builtin_dir builtin_divmod builtin_eval builtin_eval_error builtin_hash builtin_hex builtin_id builtin_issubclass builtin_len1 builtin_minmax builtin_oct builtin_ord builtin_override builtin_pow builtin_property builtin_range builtin_reversed builtin_round builtin_slice builtin_sorted builtin_sum builtin_type bytearray1 bytearray_add bytearray_append bytearray_construct bytearray_longint bytearray_slice_assign bytes bytes_add bytes_compare2 bytes_compare3 bytes_construct bytes_count bytes_find bytes_format_modulo bytes_gen bytes_large bytes_mult bytes_partition bytes_replace bytes_split bytes_strip bytes_subscr class1 class2 class3 class_bind_self class_binop class_call class_contains class_descriptor class_emptybases class_getattr class_inherit1 class_inherit_mul class_instance_override class_item class_new class_number class_staticclassmethod class_store class_store_class class_str class_super class_super_object class_use_other closure1 closure2 closure_defargs closure_manyvars closure_namedarg compare_multi comprehension1 containment continue decorator del_attr del_deref del_global del_local del_name del_subscr dict2 dict_clear dict_construct dict_copy dict_del dict_from_iter dict_fromkeys dict_get dict_intern dict_iterator dict_pop dict_popitem dict_setdefault dict_specialmeth dict_update dict_views enumerate equal equal_class errno1 except_match_tuple exception1 exception_chain exceptpoly exceptpoly2 exec1 filter floordivide for1 for2 for3 for_break for_range for_return frozenset1 frozenset_add frozenset_copy frozenset_set fun1 fun2 fun3 fun_annotations fun_calldblstar fun_calldblstar2 fun_calldblstar3 fun_callstar fun_callstardblstar fun_defargs fun_defargs2 fun_error fun_kwargs fun_kwonly fun_kwvarargs fun_largestate fun_name fun_str fun_varargs gc1 gen_yield_from gen_yield_from_close gen_yield_from_ducktype gen_yield_from_exc gen_yield_from_iter gen_yield_from_send gen_yield_from_stopped gen_yield_from_throw generator1 generator2 generator_args generator_close generator_closure generator_exc generator_send getattr getattr1 getitem globals_del hasattr1 ifcond int1 int2 int_big_and int_big_and3 int_big_cmp int_big_div int_big_error int_big_lshift int_big_mod int_big_mul int_big_or int_big_or2 int_big_or3 int_big_pow int_big_rshift int_big_unary int_big_xor int_big_xor2 int_big_xor3 int_big_zeroone int_bytes int_constfolding int_divmod int_divzero int_long int_mpz int_small is_isnot iter0 iter1 iter2 iter_of_iter lambda1 lambda_defargs lexer list1 list_clear list_compare list_copy list_count list_extend list_index list_insert list_mult list_pop list_remove list_reverse list_slice list_slice_3arg list_slice_assign list_slice_assign_grow list_sort list_sum map memoryerror memoryview1 memoryview2 memoryview_gc module1 module2 namedtuple1 object1 object_dict object_new op_error parser print python34 return1 scope seq_unpack set1 set_add set_clear set_copy set_difference set_discard set_intersection set_isdisjoint set_isfooset set_iter set_pop set_specialmeth set_symmetric_difference set_union set_unop set_update setattr1 slice_attrs slice_bignum slots_bool_len special_methods string1 string_center string_compare string_count string_cr_conversion string_crlf_conversion string_endswith string_escape string_find string_format string_format2 string_format_error string_format_modulo string_index string_join string_large string_mult string_partition string_replace string_repr string_rfind string_rindex string_rpartition string_rsplit string_slice string_split string_splitlines string_startswith string_strip struct1 struct2 subclass_classmethod subclass_native1 subclass_native2_list subclass_native2_tuple subclass_native3 subclass_native4 subclass_native5 subclass_native_buffer subclass_native_cmp subclass_native_specmeth syntaxerror try1 try2 try3 try4 try_continue try_finally2 try_finally_return try_finally_return2 tuple1 tuple_compare tuple_count tuple_index tuple_mult types1 types2 unary_op unboundlocal unpack1 while1 while_cond while_nest_exc with1 with_break with_continue with_return zip cmd_optimise cmd_showbc cmd_verbose repl_basic repl_cont btree1 framebuf1 machine_pinbase machine_pulse ticks_diff time_ms_us ubinascii_a2b_base64 ubinascii_b2a_base64 ubinascii_hexlify ubinascii_unhexlify uctypes_array_assign_le uctypes_array_assign_native_le uctypes_bytearray uctypes_le uctypes_le_float uctypes_native_float uctypes_native_le uctypes_ptr_le uctypes_ptr_native_le uctypes_sizeof uctypes_sizeof_native uheapq1 ujson_dumps ujson_dumps_extra ujson_dumps_float ujson_load ujson_loads ujson_loads_float urandom_basic urandom_extra ure1 ure_error ure_group ure_namedclass ure_split ure_split_empty uzlib_decompress array_construct builtin_float_minmax bytearray_construct bytes_construct cmath_fun_special float1 float2int_doubleprec float_array float_divmod float_divmod_relaxed float_struct int_divzero int_power list_index math_fun math_fun_special string_format string_format2 string_format_fp30 string_format_modulo string_format_modulo2 gen_context gen_context2 import1a import1b import2a import3a import_file import_pkg1 import_pkg2 import_pkg3 import_pkg4 import_pkg5 import_pkg6 rel_import_inv try_module argv buffered_writer bytesio_ext file1 file_iter file_long_read file_long_read2 file_long_read3 file_readinto file_readinto_len file_readline file_seek file_stdio open_append open_plus stringio1 stringio_with write_ext const const2 const_error decorator decorator_error emg_exc heap_lock heapalloc meminfo memstats opt_level features non_compliant non_compliant_lexer print_exception recursion recursive_data recursive_iternext rge_sm sys_exc_info dict_copy dict_create list_sort file1 file2 unicode_id unicode_index unicode_iter unicode_ord unicode_pos unicode_str_format unicode_str_modulo unicode_subscr extra_coverage ffi_callback ffi_float ffi_float2
Makefile:190: recipe for target 'test' failed
make: *** [test] Error 1

Thank you!

**Comment by robert-hh** [comment]
if you need the Unix version, better go to www.micropython.org and the repository https://github.com/micropython/micropython.

**Comment by henriqueng** [comment]
Ok. I intented to port a LWM2M (and CoAP also) library to pycom-micropython. Unfortunately, my pycom board was not delivered yet :(
